---
- name: provision
  hosts: servers
  become: yes
  roles:
    - role: geerlingguy.security

    - role: geerlingguy.nodejs

    - role: jdauphant.nginx
      vars:
        nginx_configs:
          upstream:
            - upstream app_server { server localhost:4200 fail_timeout=0; }
          nginx_sites:
            expenses:
              template: expenses.conf.j2
              server_name: "{{ nginx.server_name }}" 
